Zadanie/Zadanie/Models/ErrorViewModel.cs
namespace Zadanie.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Zadanie/Zadanie/Models/Osoby.cs
using System.ComponentModel.DataAnnotations;

namespace Zadanie.Models
{
    public class Osoby
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Brak imienia")]
        public string Imie { get; set; }
        [Required(ErrorMessage = "Brak nazwiska")]
        public string Nazwisko { get; set; }
        [Required(ErrorMessage = "Brak daty urodzenia")]
        public DateTime DataUrodzenia { get; set; }
        [Required(ErrorMessage = "Brak adresu")]
        public string Adres {  get; set; }
    }
}

Zadanie/Zadanie/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Zadanie.Models;

namespace Zadanie.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Zadanie/Zadanie/Controllers/OsobyController.cs
using Microsoft.AspNetCore.Mvc;
using Zadanie.Models;
using Zadanie.Services.Interfaces;

public class OsobyController : Controller
{
    private readonly IOsosbyServices _services;

    public OsobyController(IOsosbyServices ososbyServices)
    {
        _services = ososbyServices;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult add(Osoby osoba)
    {
        if (!ModelState.IsValid)
        {
            return View("Index", osoba);
        }

        _services.Save(osoba);
        return View("Index");
    }

    [HttpGet]
    public IActionResult showAll()
    {
        var osoby = _services.GetAll();
        return View(osoby);
    }

    [HttpGet]
    public IActionResult showById(int id)
    {
        var ososba = _services.GetById(id);
        return View("Index", ososba);
    }
}

Zadanie/Zadanie/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Zadanie/Zadanie/Views/Osoby/Index.cshtml
@model Zadanie.Models.Osoby

@using (Html.BeginForm("Add", "Osoby", FormMethod.Post))
{
    @Html.ValidationSummary()
    <h2>Dodaj osobę</h2>
    <label for="Imie">Imię:</label> @Html.TextBoxFor(m => m.Imie)
    <label for="Nazwisko">Nazwisko:</label>  @Html.TextBoxFor(m => m.Nazwisko)
    <label for="DataUrodzenia">Data urodzenia:</label> @Html.TextBoxFor(m => m.DataUrodzenia)
    <label for="Adres">Adres:</label>  @Html.TextBoxFor(m => m.Adres)
    <button type="submit">Dodaj</button>
}

@using (Html.BeginForm("ShowAll", "Osoby", FormMethod.Get))
{
    <h2>Wyświetl wszystkie osoby</h2>
    <button type="submit">Wyświetl wszystkie</button>
}

@using (Html.BeginForm("ShowById", "Osoby", FormMethod.Get))
{
    <h2>Wyświetl osobę po ID</h2>
    <label for="id">ID:</label> @Html.TextBox("id")
    <button type="submit">Wyświetl</button>
}

Zadanie/Zadanie/Views/Osoby/showAll.cshtml
@model IEnumerable<Zadanie.Models.Osoby>
@{
    ViewData["Title"] = "showAll";
}

<h1>showAll</h1>

<ol>
    @foreach (var osoba in Model)
    {
        <li>
            @osoba.ID - @osoba.Imie - @osoba.Nazwisko - @osoba.DataUrodzenia - @osoba.Adres
        </li>
    }
</ol>

Zadanie/Zadanie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zadanie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Zadanie.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Zadanie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>